package patrickstar.com.greendaodemo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_INFO".
 */
public class UserInfo {

    private String userName;
    private String realName;
    private Integer age;

    public UserInfo() {
    }

    public UserInfo(String userName) {
        this.userName = userName;
    }

    public UserInfo(String userName, String realName, Integer age) {
        this.userName = userName;
        this.realName = realName;
        this.age = age;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

}
